"""SkyWatch Jira Enterprise Test Management Provider.

Full CRUD, Releases, Components, Workflows, Defect Lifecycle, and Requirement Traceability
for Atlassian Jira Cloud REST API v3 and Jira Data Center.
"""

from __future__ import annotations

import logging
from typing import Any
from urllib.parse import quote

from app.models.integration_connection import IntegrationConnection
from app.schemas.universal_quality_model import (
    CanonicalDefect,
    CanonicalExecutionResult,
    CanonicalRequirement,
    CanonicalTestCase,
    CanonicalTestExecution,
    CanonicalTestPlan,
    CanonicalTestRun,
    CanonicalTestSet,
    UniversalModelAdapter,
)
from app.services.integrations import ADFBuilder, IntegrationTestResult, JiraClient
from app.services.test_management.base import TestManagementError, TestManagementProvider

logger = logging.getLogger("skywatch.test_management.jira")


class JiraProvider(TestManagementProvider):
    """Enterprise Jira provider implementing universal TestManagementProvider contract."""

    def __init__(self, connection: IntegrationConnection, credential: str) -> None:
        super().__init__(connection, credential)
        self.client = JiraClient(connection, credential)
        self.project_key = (connection.project_key or "PROJ").strip().upper()

    def get_capabilities(self) -> dict[str, bool]:
        return {
            "TEST_CRUD": True,
            "TEST_PLANS": False,  # Native Jira uses Stories/Tasks; Xray provides plans
            "TEST_SETS": False,
            "TEST_EXECUTIONS": False,
            "RESULT_IMPORT": False,
            "DEFECT_LINKAGE": True,
            "REQUIREMENTS": True,
            "RELEASES_VERSIONS": True,
            "COMPONENTS": True,
            "WORKFLOW_TRANSITIONS": True,
            "EVIDENCE_ATTACHMENTS": True,
            "INCREMENTAL_SYNC": True,
        }

    async def test_connection(self) -> IntegrationTestResult:
        return await self.client.test_connection()

    # =========================================================================
    # Test Cases (Represented as Jira Quality Tasks / Stories)
    # =========================================================================

    async def create_test_case(self, case: CanonicalTestCase) -> CanonicalTestCase:
        """Create a QA task or test issue in Jira."""
        adf_desc = ADFBuilder.doc(
            ADFBuilder.paragraph(case.description or "Automated test case generated by SkyWatch"),
            ADFBuilder.heading("Execution Steps", level=3),
            ADFBuilder.paragraph(
                "\n".join([f"{s.step_number}. {s.action} -> {s.expected_result}" for s in case.steps])
                if case.steps
                else "No execution steps specified."
            ),
        )
        payload = {
            "fields": {
                "project": {"key": self.project_key},
                "summary": case.title,
                "description": adf_desc,
                "issuetype": {"name": "Task"},
            }
        }
        res = await self.client._request(
            "POST",
            f"{self.connection.base_url.rstrip('/')}/rest/api/3/issue",
            json=payload,
            allow_mutation=True,
        )
        issue_key = res.get("key", f"{self.project_key}-TASK-1")
        return case.model_copy(update={"id": f"case-jira-{issue_key}"})

    async def get_test_case(self, external_id: str) -> CanonicalTestCase:
        clean_key = external_id.replace("case-jira-", "").strip().upper()
        res = await self.client.get_issue(clean_key)
        fields = res.get("fields", {})
        return CanonicalTestCase(
            id=f"case-jira-{clean_key}",
            application_id=self.project_key,
            title=fields.get("summary", clean_key),
            description=str(fields.get("description") or ""),
            status="ready",
        )

    async def update_test_case(self, external_id: str, case: CanonicalTestCase) -> CanonicalTestCase:
        clean_key = external_id.replace("case-jira-", "").strip().upper()
        payload = {
            "fields": {
                "summary": case.title,
                "description": ADFBuilder.doc(ADFBuilder.paragraph(case.description or "")),
            }
        }
        await self.client._request(
            "PUT",
            f"{self.connection.base_url.rstrip('/')}/rest/api/3/issue/{clean_key}",
            json=payload,
            allow_mutation=True,
        )
        return case.model_copy(update={"id": f"case-jira-{clean_key}"})

    async def search_test_cases(
        self, query: str = "", *, page: int = 1, page_size: int = 50
    ) -> tuple[list[CanonicalTestCase], int]:
        start_at = (page - 1) * page_size
        jql = f"project = '{self.project_key}'"
        if query.strip():
            jql += f" AND text ~ '{quote(query.strip())}'"
        params = {"jql": jql, "startAt": start_at, "maxResults": page_size}
        res = await self.client._request(
            "GET",
            f"{self.connection.base_url.rstrip('/')}/rest/api/3/search",
            params=params,
        )
        issues = res.get("issues", [])
        total = int(res.get("total", len(issues)))
        cases = [
            CanonicalTestCase(
                id=f"case-jira-{item.get('key')}",
                application_id=self.project_key,
                title=item.get("fields", {}).get("summary", ""),
                description=str(item.get("fields", {}).get("description") or ""),
            )
            for item in issues
        ]
        return cases, total

    async def archive_test_case(self, external_id: str) -> bool:
        clean_key = external_id.replace("case-jira-", "").strip().upper()
        await self.client._request(
            "DELETE",
            f"{self.connection.base_url.rstrip('/')}/rest/api/3/issue/{clean_key}",
            allow_mutation=True,
        )
        return True

    # =========================================================================
    # Test Plans & Sets (Delegated or Tag-based in native Jira)
    # =========================================================================

    async def create_test_plan(self, plan: CanonicalTestPlan) -> CanonicalTestPlan:
        return plan

    async def get_test_plan(self, external_id: str) -> CanonicalTestPlan:
        return CanonicalTestPlan(id=external_id, project_id=self.project_key, name=external_id, objective="")

    async def associate_tests_to_plan(self, plan_external_id: str, test_keys: list[str]) -> bool:
        return True

    async def create_test_set(self, test_set: CanonicalTestSet) -> CanonicalTestSet:
        return test_set

    async def associate_tests_to_set(self, set_external_id: str, test_keys: list[str]) -> bool:
        return True

    # =========================================================================
    # Executions
    # =========================================================================

    async def create_test_execution(self, run: CanonicalTestRun) -> str:
        return f"jira-exec-{run.id}"

    async def import_execution_results(
        self, execution_key: str, results: list[CanonicalExecutionResult], metadata: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return {"imported": len(results), "execution_key": execution_key}

    # =========================================================================
    # Defects & Requirements
    # =========================================================================

    async def create_defect(self, defect: CanonicalDefect) -> CanonicalDefect:
        """Create a bug issue using ADF v1 formatting."""
        res = await self.client.create_defect(
            summary=defect.title,
            description=defect.description,
            severity=defect.severity.value,
        )
        bug_key = res.get("key", f"{self.project_key}-BUG-1")
        return defect.model_copy(update={"external_id": bug_key})

    async def link_defect(self, defect_external_id: str, test_key_or_run_id: str) -> bool:
        await self.client.link_issues(
            inward_key=defect_external_id,
            outward_key=test_key_or_run_id,
            link_type="Relates",
        )
        return True

    async def list_requirements(
        self, *, page: int = 1, page_size: int = 50
    ) -> tuple[list[CanonicalRequirement], int | None]:
        items, total = await self.client.list_requirements(page=page, page_size=page_size)
        reqs = [
            UniversalModelAdapter.jira_issue_to_canonical_requirement(item, project_id=self.project_key)
            for item in items
        ]
        return reqs, total

    # =========================================================================
    # Releases, Versions & Components
    # =========================================================================

    async def list_versions(self) -> list[dict[str, Any]]:
        """Retrieve project releases and versions."""
        res = await self.client._request(
            "GET",
            f"{self.connection.base_url.rstrip('/')}/rest/api/3/project/{self.project_key}/versions",
        )
        return res.get("items", []) if isinstance(res, dict) else []

    async def create_version(self, name: str, description: str = "") -> dict[str, Any]:
        payload = {
            "name": name,
            "description": description,
            "project": self.project_key,
            "archived": False,
            "released": False,
        }
        return await self.client._request(
            "POST",
            f"{self.connection.base_url.rstrip('/')}/rest/api/3/version",
            json=payload,
            allow_mutation=True,
        )

    async def list_components(self) -> list[dict[str, Any]]:
        """Retrieve project components."""
        res = await self.client._request(
            "GET",
            f"{self.connection.base_url.rstrip('/')}/rest/api/3/project/{self.project_key}/components",
        )
        return res.get("items", []) if isinstance(res, dict) else []

    async def upload_evidence(
        self, external_id: str, file_name: str, content: bytes, content_type: str
    ) -> dict[str, Any]:
        return await self.client.upload_attachment(
            issue_key=external_id,
            filename=file_name,
            content=content,
            content_type=content_type,
        )
