"""Cypress 13.x JavaScript test script generator.

Translates the framework-agnostic IR (steps/checks) into idiomatic Cypress
``describe`` / ``it`` blocks using ``cy.visit()``, ``cy.get()``, etc.
"""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING

from .base import ScriptGenerator

if TYPE_CHECKING:
    from app.models.application import Application
    from app.models.test_case import TestCase


class CypressGenerator(ScriptGenerator):
    """Generates Cypress JavaScript test specs (.cy.js)."""

    def framework_name(self) -> str:
        return "Cypress JavaScript"

    def language(self) -> str:
        return "javascript"

    def file_extension(self) -> str:
        return ".cy.js"

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_value(val: str | None, test_data: dict[str, str]) -> str:
        """Resolve ``{{token}}`` placeholders into Cypress env references."""
        if not val:
            return "''"
        match = re.fullmatch(r"\{\{\s*([A-Za-z0-9_.\-]+)\s*\}\}", val.strip())
        if match:
            tok = match.group(1).strip()
            fallback = test_data.get(tok, tok).replace("'", "\\'")
            return f"Cypress.env('{tok}') || '{fallback}'"
        if "{{" in val and "}}" in val:
            def _sub(m: re.Match) -> str:
                tok = m.group(1).strip()
                fallback = test_data.get(tok, tok).replace("'", "\\'")
                return f"${{Cypress.env('{tok}') || '{fallback}'}}"
            interpolated = re.sub(r"\{\{\s*([A-Za-z0-9_.\-]+)\s*\}\}", _sub, val)
            return f"`{interpolated}`"
        return f"'{val.replace(chr(39), chr(92) + chr(39))}'"

    @staticmethod
    def _selector(sel: str | None) -> str:
        """Map IR selectors to Cypress-compatible selectors."""
        if not sel:
            return "'body'"
        s = sel.strip()
        # text= selectors → :contains()
        if s.startswith("text="):
            text_val = s[5:].replace("'", "\\'")
            return f"':contains(\"{text_val}\")'"
        # label= selectors → [aria-label] or label association
        if s.startswith("label="):
            label_val = s[6:].replace("'", "\\'")
            return f"'[aria-label=\"{label_val}\"], label:contains(\"{label_val}\") + input, label:contains(\"{label_val}\") + select, label:contains(\"{label_val}\") + textarea'"
        # a:has-text('...') → a:contains(...)
        has_text_match = re.match(r"a:has-text\('([^']+)'\)", s)
        if has_text_match:
            text_val = has_text_match.group(1).replace("'", "\\'")
            return f"'a:contains(\"{text_val}\")'"
        return f"'{s.replace(chr(39), chr(92) + chr(39))}'"

    # ------------------------------------------------------------------
    # Code generation
    # ------------------------------------------------------------------

    def generate_code(
        self,
        test_case: "TestCase",
        application: "Application",
        steps: list[dict],
        checks: list[dict],
    ) -> str:
        title = self.safe_title(test_case)
        lines: list[str] = [
            "/// <reference types=\"cypress\" />",
            "",
            "/**",
            f" * Test Case: {title}",
            f" * Application: {application.name} ({application.target})",
            f" * Category: {getattr(test_case, 'category', 'functional')}",
            f" * Priority: {getattr(test_case, 'priority', 'medium')}",
        ]
        preconditions = getattr(test_case, "preconditions", None)
        if preconditions:
            lines.append(f" * Preconditions: {preconditions.strip()}")
        lines.extend([
            " * Framework: Cypress 13.x",
            " * Generated by SkyWatch Automation Engine",
            " */",
            "",
            f"describe('{self.escape_single_quotes(title)}', () => {{",
            f"  it('{self.escape_single_quotes(title)}', () => {{",
        ])

        # Build test data map
        test_data = self._build_test_data(test_case, steps)
        if test_data:
            lines.append("    // Parameterized test data")
            lines.append("    const testData = {")
            for k, v in test_data.items():
                env_var = re.sub(r"[^A-Za-z0-9_]+", "_", k.upper()).strip("_")
                clean_v = v.replace("'", "\\'")
                lines.append(f"      {k}: Cypress.env('{env_var}') || '{clean_v}',")
            lines.append("    };")
            lines.append("")

        # Steps
        for idx, step in enumerate(steps, 1):
            act = step.get("action")
            sel = step.get("selector")
            val = step.get("value")
            desc = step.get("description") or f"Step {idx}: {act}"
            lines.append(f"    // {idx}. {desc}")

            if act == "navigate":
                target_url = val or application.target
                lines.append(f"    cy.visit({self._resolve_value(target_url, test_data)});")
            elif act in {"reload", "refresh"}:
                lines.append("    cy.reload();")
            elif act in {"go_back", "navigate_back"}:
                lines.append("    cy.go('back');")
            elif act == "click":
                lines.append(f"    cy.get({self._selector(sel)}).first().click();")
            elif act == "type":
                lines.append(f"    cy.get({self._selector(sel)}).first().clear().type({self._resolve_value(val, test_data)});")
            elif act == "select":
                lines.append(f"    cy.get({self._selector(sel)}).first().select({self._resolve_value(val, test_data)});")
            elif act == "check":
                lines.append(f"    cy.get({self._selector(sel)}).first().check();")
            elif act == "uncheck":
                lines.append(f"    cy.get({self._selector(sel)}).first().uncheck();")
            elif act == "assert_visible":
                lines.append(f"    cy.get({self._selector(sel)}).first().should('be.visible');")
            elif act == "assert_text":
                clean_val = (val or "").replace("'", "\\'")
                lines.append(f"    cy.get({self._selector(sel)}).first().should('contain', '{clean_val}');")
            elif act == "assert_title":
                clean_val = (val or "").replace("'", "\\'")
                lines.append(f"    cy.title().should('match', /{clean_val}/i);")
            elif act == "assert_url_contains":
                clean_val = (val or "").replace("'", "\\'")
                lines.append(f"    cy.url().should('include', '{clean_val}');")
            lines.append("")

        # Post-condition checks
        if checks:
            lines.append("    // Post-Condition Assertions")
            for check in checks:
                ctype = check.get("type")
                cval = (check.get("value") or "").replace("'", "\\'")
                if ctype == "visible":
                    lines.append(f"    cy.get('{cval}').first().should('be.visible');")
                elif ctype == "text_contains":
                    lines.append(f"    cy.get('body').should('contain', '{cval}');")
                elif ctype == "title_contains":
                    lines.append(f"    cy.title().should('match', /{cval}/i);")

        lines.extend([
            "  });",
            "});",
            "",
        ])
        return "\n".join(lines)

    @staticmethod
    def _build_test_data(test_case: "TestCase", steps: list[dict]) -> dict[str, str]:
        """Extract parameterized test data from the test case and steps."""
        case_test_data: dict[str, str] = {}
        raw_td = getattr(test_case, "test_data", None)
        if isinstance(raw_td, dict):
            case_test_data = {str(k): str(v) for k, v in raw_td.items() if not str(k).startswith("_")}
        elif isinstance(raw_td, str) and raw_td.strip():
            try:
                p_td = json.loads(raw_td)
                if isinstance(p_td, dict):
                    case_test_data = {str(k): str(v) for k, v in p_td.items() if not str(k).startswith("_")}
            except Exception:
                pass
        for step in steps:
            val = step.get("value") or ""
            for match in re.findall(r"\{\{\s*([A-Za-z0-9_.\-]+)\s*\}\}", val):
                tok = match.strip()
                if tok and tok not in case_test_data:
                    from app.services.ai_service import synthesize_parameter_value
                    case_test_data[tok] = synthesize_parameter_value(tok, getattr(test_case, "category", "positive"))
        return case_test_data
