"""Java TestNG + Selenium WebDriver test script generator.

Translates the framework-agnostic IR into Java TestNG test classes using
Selenium 4 WebDriver with explicit waits.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from .base import ScriptGenerator

if TYPE_CHECKING:
    from app.models.application import Application
    from app.models.test_case import TestCase


class JavaTestNGGenerator(ScriptGenerator):
    """Generates Java TestNG + Selenium test classes (.java)."""

    def framework_name(self) -> str:
        return "Java TestNG + Selenium"

    def language(self) -> str:
        return "java"

    def file_extension(self) -> str:
        return ".java"

    def file_naming(self, test_case: "TestCase") -> str:
        words = re.sub(r"[^\w\s]", "", test_case.title).strip().split()
        class_name = "".join(w.capitalize() for w in words[:8]) or f"TC{test_case.id:02d}"
        return f"{class_name}Test.java"

    # ------------------------------------------------------------------

    @staticmethod
    def _java_by(sel: str | None) -> str:
        """Convert IR selector to Java By.* expression."""
        if not sel:
            return 'By.tagName("body")'
        s = sel.strip()
        if s.startswith("text="):
            text_val = s[5:].replace('"', '\\"')
            return f'By.xpath("//*[contains(text(), \\"{text_val}\\")]")'
        if s.startswith("label="):
            label_val = s[6:].replace('"', '\\"')
            return f'By.xpath("//label[contains(text(), \\"{label_val}\\")]/following-sibling::*[self::input or self::select or self::textarea][1]")'
        has_text = re.match(r"a:has-text\('([^']+)'\)", s)
        if has_text:
            text_val = has_text.group(1).replace('"', '\\"')
            return f'By.xpath("//a[contains(text(), \\"{text_val}\\")]")'
        if s.startswith("#"):
            return f'By.id("{s[1:]}")'
        if s.startswith("."):
            return f'By.className("{s[1:]}")'
        # Multi-selector: take first
        first = s.split(",")[0].strip() if "," in s else s
        return f'By.cssSelector("{first.replace(chr(34), chr(92) + chr(34))}")'

    @staticmethod
    def _java_str(val: str | None) -> str:
        if not val:
            return '""'
        return f'"{val.replace(chr(34), chr(92) + chr(34))}"'

    # ------------------------------------------------------------------

    def generate_code(
        self,
        test_case: "TestCase",
        application: "Application",
        steps: list[dict],
        checks: list[dict],
    ) -> str:
        title = self.safe_title(test_case)
        words = re.sub(r"[^\w\s]", "", test_case.title).strip().split()
        class_name = "".join(w.capitalize() for w in words[:8]) or f"TC{test_case.id:02d}"
        method_name = re.sub(r"[^\w]", "_", title.lower()).strip("_") or f"tc_{test_case.id}"

        lines: list[str] = [
            "package tests.generated;",
            "",
            "import org.openqa.selenium.*;",
            "import org.openqa.selenium.chrome.ChromeDriver;",
            "import org.openqa.selenium.chrome.ChromeOptions;",
            "import org.openqa.selenium.support.ui.ExpectedConditions;",
            "import org.openqa.selenium.support.ui.Select;",
            "import org.openqa.selenium.support.ui.WebDriverWait;",
            "import org.testng.Assert;",
            "import org.testng.annotations.*;",
            "import java.time.Duration;",
            "",
            "/**",
            f" * Test Case: {title}",
            f" * Application: {application.name} ({application.target})",
            f" * Category: {getattr(test_case, 'category', 'functional')}",
            f" * Priority: {getattr(test_case, 'priority', 'medium')}",
            " * Framework: Java TestNG + Selenium 4",
            " * Generated by SkyWatch Automation Engine",
            " */",
            f"public class {class_name}Test {{",
            "",
            "    private WebDriver driver;",
            "    private WebDriverWait wait;",
            "",
            "    @BeforeMethod",
            "    public void setUp() {",
            '        ChromeOptions options = new ChromeOptions();',
            '        String headless = System.getenv("HEADLESS");',
            '        if (headless == null || headless.equalsIgnoreCase("true") || headless.equals("1")) {',
            '            options.addArguments("--headless=new");',
            "        }",
            '        options.addArguments("--no-sandbox", "--disable-dev-shm-usage", "--window-size=1920,1080");',
            "        driver = new ChromeDriver(options);",
            "        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));",
            "        wait = new WebDriverWait(driver, Duration.ofSeconds(15));",
            "    }",
            "",
            "    @AfterMethod",
            "    public void tearDown() {",
            "        if (driver != null) {",
            "            driver.quit();",
            "        }",
            "    }",
            "",
            "    @Test",
            f"    public void test_{method_name}() {{",
        ]

        for idx, step in enumerate(steps, 1):
            act = step.get("action")
            sel = step.get("selector")
            val = step.get("value")
            desc = step.get("description") or f"Step {idx}: {act}"
            lines.append(f"        // {idx}. {desc}")

            if act == "navigate":
                target = val or application.target
                lines.append(f"        driver.get({self._java_str(target)});")
            elif act in {"reload", "refresh"}:
                lines.append("        driver.navigate().refresh();")
            elif act in {"go_back", "navigate_back"}:
                lines.append("        driver.navigate().back();")
            elif act == "click":
                by = self._java_by(sel)
                lines.append(f"        wait.until(ExpectedConditions.elementToBeClickable({by}));")
                lines.append(f"        driver.findElement({by}).click();")
            elif act == "type":
                by = self._java_by(sel)
                lines.append(f"        wait.until(ExpectedConditions.visibilityOfElementLocated({by}));")
                lines.append(f"        driver.findElement({by}).clear();")
                lines.append(f"        driver.findElement({by}).sendKeys({self._java_str(val)});")
            elif act == "select":
                by = self._java_by(sel)
                lines.append(f"        wait.until(ExpectedConditions.visibilityOfElementLocated({by}));")
                lines.append(f"        new Select(driver.findElement({by})).selectByVisibleText({self._java_str(val)});")
            elif act == "check":
                by = self._java_by(sel)
                lines.append(f"        WebElement checkbox = wait.until(ExpectedConditions.elementToBeClickable({by}));")
                lines.append("        if (!checkbox.isSelected()) { checkbox.click(); }")
            elif act == "uncheck":
                by = self._java_by(sel)
                lines.append(f"        WebElement checkbox = wait.until(ExpectedConditions.elementToBeClickable({by}));")
                lines.append("        if (checkbox.isSelected()) { checkbox.click(); }")
            elif act == "assert_visible":
                by = self._java_by(sel)
                lines.append(f"        wait.until(ExpectedConditions.visibilityOfElementLocated({by}));")
            elif act == "assert_text":
                by = self._java_by(sel)
                clean_val = (val or "").replace('"', '\\"')
                lines.append(f"        wait.until(ExpectedConditions.visibilityOfElementLocated({by}));")
                lines.append(f'        Assert.assertTrue(driver.findElement({by}).getText().contains("{clean_val}"),')
                lines.append(f'            "Expected text \\"{clean_val}\\" not found");')
            elif act == "assert_title":
                clean_val = (val or "").replace('"', '\\"')
                lines.append(f'        Assert.assertTrue(driver.getTitle().toLowerCase().contains("{clean_val}".toLowerCase()),')
                lines.append(f'            "Expected title containing \\"{clean_val}\\"");')
            elif act == "assert_url_contains":
                clean_val = (val or "").replace('"', '\\"')
                lines.append(f'        Assert.assertTrue(driver.getCurrentUrl().contains("{clean_val}"),')
                lines.append(f'            "Expected URL containing \\"{clean_val}\\"");')
            lines.append("")

        # Post-condition checks
        if checks:
            lines.append("        // Post-Condition Assertions")
            for check in checks:
                ctype = check.get("type")
                cval = (check.get("value") or "").replace('"', '\\"')
                if ctype == "visible":
                    lines.append(f'        wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("{cval}")));')
                elif ctype == "text_contains":
                    lines.append(f'        Assert.assertTrue(driver.findElement(By.tagName("body")).getText().contains("{cval}"));')
                elif ctype == "title_contains":
                    lines.append(f'        Assert.assertTrue(driver.getTitle().toLowerCase().contains("{cval}".toLowerCase()));')

        lines.extend([
            "    }",
            "}",
            "",
        ])
        return "\n".join(lines)
