"""Jest + Puppeteer JavaScript test script generator.

Translates the framework-agnostic IR into Jest test files using Puppeteer
for browser automation with ``page.goto()``, ``page.click()``, etc.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from .base import ScriptGenerator

if TYPE_CHECKING:
    from app.models.application import Application
    from app.models.test_case import TestCase


class JestPuppeteerGenerator(ScriptGenerator):
    """Generates Jest + Puppeteer JavaScript test files (.test.js)."""

    def framework_name(self) -> str:
        return "Jest + Puppeteer"

    def language(self) -> str:
        return "javascript"

    def file_extension(self) -> str:
        return ".test.js"

    # ------------------------------------------------------------------

    @staticmethod
    def _pptr_selector(sel: str | None) -> str:
        """Map IR selector to Puppeteer-compatible selector or XPath."""
        if not sel:
            return "'body'"
        s = sel.strip()
        if s.startswith("text="):
            text_val = s[5:].replace("'", "\\'")
            return f"'::-p-text({text_val})'"
        if s.startswith("label="):
            label_val = s[6:].replace("'", "\\'")
            return f"'[aria-label=\"{label_val}\"]'"
        has_text = re.match(r"a:has-text\('([^']+)'\)", s)
        if has_text:
            text_val = has_text.group(1).replace("'", "\\'")
            return f"'::-p-text({text_val})'"
        # Multi-selector: take first
        if "," in s:
            first = s.split(",")[0].strip()
            return f"'{first.replace(chr(39), chr(92) + chr(39))}'"
        return f"'{s.replace(chr(39), chr(92) + chr(39))}'"

    @staticmethod
    def _pptr_val(val: str | None) -> str:
        if not val:
            return "''"
        return f"'{val.replace(chr(39), chr(92) + chr(39))}'"

    # ------------------------------------------------------------------

    def generate_code(
        self,
        test_case: "TestCase",
        application: "Application",
        steps: list[dict],
        checks: list[dict],
    ) -> str:
        title = self.safe_title(test_case)
        lines: list[str] = [
            "/**",
            f" * Test Case: {title}",
            f" * Application: {application.name} ({application.target})",
            f" * Category: {getattr(test_case, 'category', 'functional')}",
            f" * Priority: {getattr(test_case, 'priority', 'medium')}",
            " * Framework: Jest + Puppeteer",
            " * Generated by SkyWatch Automation Engine",
            " */",
            "",
            "const puppeteer = require('puppeteer');",
            "",
            f"describe('{self.escape_single_quotes(title)}', () => {{",
            "  let browser;",
            "  let page;",
            "",
            "  beforeAll(async () => {",
            "    browser = await puppeteer.launch({",
            "      headless: process.env.HEADLESS !== 'false' ? 'new' : false,",
            "      args: ['--no-sandbox', '--disable-dev-shm-usage', '--window-size=1920,1080'],",
            "    });",
            "    page = await browser.newPage();",
            "    await page.setViewport({ width: 1920, height: 1080 });",
            "  });",
            "",
            "  afterAll(async () => {",
            "    if (browser) await browser.close();",
            "  });",
            "",
            f"  test('{self.escape_single_quotes(title)}', async () => {{",
            "    jest.setTimeout(60000);",
            "",
        ]

        for idx, step in enumerate(steps, 1):
            act = step.get("action")
            sel = step.get("selector")
            val = step.get("value")
            desc = step.get("description") or f"Step {idx}: {act}"
            lines.append(f"    // {idx}. {desc}")

            if act == "navigate":
                target = val or application.target
                lines.append(f"    await page.goto({self._pptr_val(target)}, {{ waitUntil: 'domcontentloaded' }});")
            elif act in {"reload", "refresh"}:
                lines.append("    await page.reload({ waitUntil: 'domcontentloaded' });")
            elif act in {"go_back", "navigate_back"}:
                lines.append("    await page.goBack({ waitUntil: 'domcontentloaded' });")
            elif act == "click":
                lines.append(f"    await page.waitForSelector({self._pptr_selector(sel)}, {{ visible: true, timeout: 15000 }});")
                lines.append(f"    await page.click({self._pptr_selector(sel)});")
            elif act == "type":
                lines.append(f"    await page.waitForSelector({self._pptr_selector(sel)}, {{ visible: true, timeout: 15000 }});")
                lines.append(f"    const input_{idx} = await page.$({self._pptr_selector(sel)});")
                lines.append(f"    await input_{idx}.click({{ clickCount: 3 }});")
                lines.append(f"    await input_{idx}.type({self._pptr_val(val)});")
            elif act == "select":
                lines.append(f"    await page.waitForSelector({self._pptr_selector(sel)}, {{ visible: true, timeout: 15000 }});")
                lines.append(f"    await page.select({self._pptr_selector(sel)}, {self._pptr_val(val)});")
            elif act == "check":
                lines.append(f"    await page.waitForSelector({self._pptr_selector(sel)}, {{ visible: true, timeout: 15000 }});")
                lines.append(f"    const cb_{idx} = await page.$({self._pptr_selector(sel)});")
                lines.append(f"    const checked_{idx} = await (await cb_{idx}.getProperty('checked')).jsonValue();")
                lines.append(f"    if (!checked_{idx}) await cb_{idx}.click();")
            elif act == "uncheck":
                lines.append(f"    await page.waitForSelector({self._pptr_selector(sel)}, {{ visible: true, timeout: 15000 }});")
                lines.append(f"    const cb_{idx} = await page.$({self._pptr_selector(sel)});")
                lines.append(f"    const checked_{idx} = await (await cb_{idx}.getProperty('checked')).jsonValue();")
                lines.append(f"    if (checked_{idx}) await cb_{idx}.click();")
            elif act == "assert_visible":
                lines.append(f"    await page.waitForSelector({self._pptr_selector(sel)}, {{ visible: true, timeout: 15000 }});")
            elif act == "assert_text":
                clean_val = (val or "").replace("'", "\\'")
                lines.append(f"    const text_{idx} = await page.$eval({self._pptr_selector(sel)}, el => el.textContent);")
                lines.append(f"    expect(text_{idx}).toContain('{clean_val}');")
            elif act == "assert_title":
                clean_val = (val or "").replace("'", "\\'")
                lines.append(f"    const pageTitle_{idx} = await page.title();")
                lines.append(f"    expect(pageTitle_{idx}.toLowerCase()).toContain('{clean_val}'.toLowerCase());")
            elif act == "assert_url_contains":
                clean_val = (val or "").replace("'", "\\'")
                lines.append(f"    expect(page.url()).toContain('{clean_val}');")
            lines.append("")

        # Post-condition checks
        if checks:
            lines.append("    // Post-Condition Assertions")
            for check in checks:
                ctype = check.get("type")
                cval = (check.get("value") or "").replace("'", "\\'")
                if ctype == "visible":
                    lines.append(f"    await page.waitForSelector('{cval}', {{ visible: true, timeout: 15000 }});")
                elif ctype == "text_contains":
                    lines.append(f"    const bodyText = await page.$eval('body', el => el.textContent);")
                    lines.append(f"    expect(bodyText).toContain('{cval}');")
                elif ctype == "title_contains":
                    lines.append(f"    const title = await page.title();")
                    lines.append(f"    expect(title.toLowerCase()).toContain('{cval}'.toLowerCase());")

        lines.extend([
            "  });",
            "});",
            "",
        ])
        return "\n".join(lines)
