"""Robot Framework test script generator.

Translates the framework-agnostic IR into Robot Framework ``.robot`` files
using SeleniumLibrary keywords.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from .base import ScriptGenerator

if TYPE_CHECKING:
    from app.models.application import Application
    from app.models.test_case import TestCase


class RobotFrameworkGenerator(ScriptGenerator):
    """Generates Robot Framework test files (.robot)."""

    def framework_name(self) -> str:
        return "Robot Framework"

    def language(self) -> str:
        return "robotframework"

    def file_extension(self) -> str:
        return ".robot"

    # ------------------------------------------------------------------

    @staticmethod
    def _rf_selector(sel: str | None) -> str:
        """Map IR selectors to Robot Framework / SeleniumLibrary locators."""
        if not sel:
            return "tag=body"
        s = sel.strip()
        if s.startswith("text="):
            return f"xpath=//*[contains(text(), '{s[5:]}')]"
        if s.startswith("label="):
            label = s[6:]
            return f"xpath=//label[contains(text(), '{label}')]/following-sibling::*[self::input or self::select or self::textarea][1] | //*[@aria-label='{label}']"
        has_text = re.match(r"a:has-text\('([^']+)'\)", s)
        if has_text:
            return f"xpath=//a[contains(text(), '{has_text.group(1)}')]"
        if s.startswith("#"):
            return f"id={s[1:]}"
        if "," in s:
            # Multi-selector: take the first one
            first = s.split(",")[0].strip()
            return f"css={first}"
        return f"css={s}"

    # ------------------------------------------------------------------

    def generate_code(
        self,
        test_case: "TestCase",
        application: "Application",
        steps: list[dict],
        checks: list[dict],
    ) -> str:
        title = self.safe_title(test_case)
        lines: list[str] = []

        # Settings section
        lines.extend([
            "*** Settings ***",
            "Documentation    " + title,
            f"...              Application: {application.name} ({application.target})",
            f"...              Category: {getattr(test_case, 'category', 'functional')}",
            f"...              Priority: {getattr(test_case, 'priority', 'medium')}",
            "...              Generated by SkyWatch Automation Engine",
            "Library          SeleniumLibrary",
            "Library          Collections",
            "Library          String",
            "Test Setup       Open Browser    about:blank    chrome",
            "...              options=add_argument(\"--headless=new\");add_argument(\"--no-sandbox\");add_argument(\"--window-size=1920,1080\")",
            "Test Teardown    Close All Browsers",
            "",
        ])

        # Variables section
        lines.extend([
            "*** Variables ***",
            f"${{TARGET_URL}}    {application.target or 'https://example.com'}",
            f"${{TIMEOUT}}       15s",
        ])
        # Add test data variables
        raw_td = getattr(test_case, "test_data", None)
        if isinstance(raw_td, dict):
            for k, v in raw_td.items():
                if not str(k).startswith("_"):
                    var_name = re.sub(r"[^A-Za-z0-9_]", "_", str(k).upper()).strip("_")
                    lines.append(f"${{{var_name}}}    {v}")
        lines.append("")

        # Test Cases section
        lines.extend([
            "*** Test Cases ***",
            title,
            f"    [Documentation]    {title}",
        ])
        preconditions = getattr(test_case, "preconditions", None)
        if preconditions:
            lines.append(f"    ...                Preconditions: {preconditions.strip()}")

        for idx, step in enumerate(steps, 1):
            act = step.get("action")
            sel = step.get("selector")
            val = step.get("value")
            desc = step.get("description") or f"Step {idx}: {act}"
            lines.append(f"    # {idx}. {desc}")

            if act == "navigate":
                target = val or application.target or "${TARGET_URL}"
                lines.append(f"    Go To    {target}")
                lines.append(f"    Wait Until Page Contains Element    tag=body    timeout=${{TIMEOUT}}")
            elif act in {"reload", "refresh"}:
                lines.append("    Reload Page")
            elif act in {"go_back", "navigate_back"}:
                lines.append("    Go Back")
            elif act == "click":
                loc = self._rf_selector(sel)
                lines.append(f"    Wait Until Element Is Visible    {loc}    timeout=${{TIMEOUT}}")
                lines.append(f"    Click Element    {loc}")
            elif act == "type":
                loc = self._rf_selector(sel)
                rf_val = val or ""
                lines.append(f"    Wait Until Element Is Visible    {loc}    timeout=${{TIMEOUT}}")
                lines.append(f"    Clear Element Text    {loc}")
                lines.append(f"    Input Text    {loc}    {rf_val}")
            elif act == "select":
                loc = self._rf_selector(sel)
                rf_val = val or ""
                lines.append(f"    Wait Until Element Is Visible    {loc}    timeout=${{TIMEOUT}}")
                lines.append(f"    Select From List By Label    {loc}    {rf_val}")
            elif act == "check":
                loc = self._rf_selector(sel)
                lines.append(f"    Wait Until Element Is Visible    {loc}    timeout=${{TIMEOUT}}")
                lines.append(f"    Select Checkbox    {loc}")
            elif act == "uncheck":
                loc = self._rf_selector(sel)
                lines.append(f"    Wait Until Element Is Visible    {loc}    timeout=${{TIMEOUT}}")
                lines.append(f"    Unselect Checkbox    {loc}")
            elif act == "assert_visible":
                loc = self._rf_selector(sel)
                lines.append(f"    Wait Until Element Is Visible    {loc}    timeout=${{TIMEOUT}}")
            elif act == "assert_text":
                clean_val = val or ""
                lines.append(f"    Wait Until Page Contains    {clean_val}    timeout=${{TIMEOUT}}")
            elif act == "assert_title":
                clean_val = val or ""
                lines.append(f"    Title Should Contain    {clean_val}")
            elif act == "assert_url_contains":
                clean_val = val or ""
                lines.append(f"    ${{current_url}}=    Get Location")
                lines.append(f"    Should Contain    ${{current_url}}    {clean_val}")

        # Post-condition checks
        if checks:
            lines.append("    # Post-Condition Assertions")
            for check in checks:
                ctype = check.get("type")
                cval = check.get("value") or ""
                if ctype == "visible":
                    lines.append(f"    Wait Until Element Is Visible    {self._rf_selector(cval)}    timeout=${{TIMEOUT}}")
                elif ctype == "text_contains":
                    lines.append(f"    Wait Until Page Contains    {cval}    timeout=${{TIMEOUT}}")
                elif ctype == "title_contains":
                    lines.append(f"    Title Should Contain    {cval}")

        lines.append("")
        return "\n".join(lines)
