"""Selenium 4 + pytest Python test script generator.

Translates the framework-agnostic IR into idiomatic Selenium WebDriver Python
code using ``pytest`` test functions with ``WebDriverWait`` explicit waits.
"""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING

from .base import ScriptGenerator

if TYPE_CHECKING:
    from app.models.application import Application
    from app.models.test_case import TestCase


class SeleniumPythonGenerator(ScriptGenerator):
    """Generates Selenium 4 + pytest Python test scripts (test_*.py)."""

    def framework_name(self) -> str:
        return "Selenium Python"

    def language(self) -> str:
        return "python"

    def file_extension(self) -> str:
        return ".py"

    def file_naming(self, test_case: "TestCase") -> str:
        safe_name = re.sub(r"[^\w]", "_", test_case.title.lower()).strip("_")
        return f"test_{safe_name or f'tc_{test_case.id}'}.py"

    # ------------------------------------------------------------------

    @staticmethod
    def _py_selector(sel: str | None) -> tuple[str, str]:
        """Convert IR selector into a (By.*, value) pair for Selenium."""
        if not sel:
            return "By.TAG_NAME", "body"
        s = sel.strip()
        if s.startswith("text="):
            text_val = s[5:].replace('"', '\\"')
            return "By.XPATH", f'//*[contains(text(), "{text_val}")]'
        if s.startswith("label="):
            label_val = s[6:].replace('"', '\\"')
            return "By.XPATH", f'//label[contains(text(), "{label_val}")]/following-sibling::*[self::input or self::select or self::textarea][1] | //*[@aria-label="{label_val}"]'
        has_text_match = re.match(r"a:has-text\('([^']+)'\)", s)
        if has_text_match:
            text_val = has_text_match.group(1).replace('"', '\\"')
            return "By.XPATH", f'//a[contains(text(), "{text_val}")]'
        if s.startswith("#"):
            return "By.ID", s[1:]
        if s.startswith("."):
            return "By.CLASS_NAME", s[1:]
        # Fallback to CSS selector
        return "By.CSS_SELECTOR", s

    @staticmethod
    def _py_str(val: str | None, test_data: dict[str, str]) -> str:
        """Resolve value to a Python string expression."""
        if not val:
            return '""'
        match = re.fullmatch(r"\{\{\s*([A-Za-z0-9_.\-]+)\s*\}\}", val.strip())
        if match:
            tok = match.group(1).strip()
            env_var = re.sub(r"[^A-Za-z0-9_]+", "_", tok.upper()).strip("_")
            fallback = test_data.get(tok, tok).replace('"', '\\"')
            return f'os.environ.get("{env_var}", "{fallback}")'
        clean = val.replace('"', '\\"')
        return f'"{clean}"'

    # ------------------------------------------------------------------

    def generate_code(
        self,
        test_case: "TestCase",
        application: "Application",
        steps: list[dict],
        checks: list[dict],
    ) -> str:
        title = self.safe_title(test_case)
        test_data = self._build_test_data(test_case, steps)
        func_name = re.sub(r"[^\w]", "_", title.lower()).strip("_") or f"tc_{test_case.id}"

        lines: list[str] = [
            '"""',
            f"Test Case: {title}",
            f"Application: {application.name} ({application.target})",
            f"Category: {getattr(test_case, 'category', 'functional')}",
            f"Priority: {getattr(test_case, 'priority', 'medium')}",
            "Framework: Selenium 4 + pytest",
            "Generated by SkyWatch Automation Engine",
            '"""',
            "",
            "import os",
            "import pytest",
            "from selenium import webdriver",
            "from selenium.webdriver.common.by import By",
            "from selenium.webdriver.support.ui import WebDriverWait, Select",
            "from selenium.webdriver.support import expected_conditions as EC",
            "",
            "",
            "@pytest.fixture",
            "def driver():",
            '    """Set up Chrome WebDriver with headless option support."""',
            "    options = webdriver.ChromeOptions()",
            '    if os.environ.get("HEADLESS", "true").lower() in ("true", "1"):',
            '        options.add_argument("--headless=new")',
            '    options.add_argument("--no-sandbox")',
            '    options.add_argument("--disable-dev-shm-usage")',
            '    options.add_argument("--window-size=1920,1080")',
            "    _driver = webdriver.Chrome(options=options)",
            "    _driver.implicitly_wait(10)",
            "    yield _driver",
            "    _driver.quit()",
            "",
            "",
        ]

        # Test data constants
        if test_data:
            lines.append("# Parameterized test data")
            lines.append("TEST_DATA = {")
            for k, v in test_data.items():
                env_var = re.sub(r"[^A-Za-z0-9_]+", "_", k.upper()).strip("_")
                clean_v = v.replace('"', '\\"')
                lines.append(f'    "{k}": os.environ.get("{env_var}", "{clean_v}"),')
            lines.append("}")
            lines.append("")
            lines.append("")

        # Test function
        lines.append(f"def test_{func_name}(driver):")
        lines.append(f'    """')
        lines.append(f"    {title}")
        preconditions = getattr(test_case, "preconditions", None)
        if preconditions:
            lines.append(f"    Preconditions: {preconditions.strip()}")
        lines.append(f'    """')
        lines.append("    wait = WebDriverWait(driver, 15)")
        lines.append("")

        for idx, step in enumerate(steps, 1):
            act = step.get("action")
            sel = step.get("selector")
            val = step.get("value")
            desc = step.get("description") or f"Step {idx}: {act}"
            lines.append(f"    # {idx}. {desc}")

            if act == "navigate":
                target = val or application.target
                lines.append(f"    driver.get({self._py_str(target, test_data)})")
            elif act in {"reload", "refresh"}:
                lines.append("    driver.refresh()")
            elif act in {"go_back", "navigate_back"}:
                lines.append("    driver.back()")
            elif act == "click":
                by, value = self._py_selector(sel)
                lines.append(f'    wait.until(EC.element_to_be_clickable(({by}, {self._py_str(value, {})})))')
                lines.append(f"    driver.find_element({by}, {self._py_str(value, {})}).click()")
            elif act == "type":
                by, value = self._py_selector(sel)
                lines.append(f'    element = wait.until(EC.visibility_of_element_located(({by}, {self._py_str(value, {})})))')
                lines.append(f"    element.clear()")
                lines.append(f"    element.send_keys({self._py_str(val, test_data)})")
            elif act == "select":
                by, value = self._py_selector(sel)
                lines.append(f'    select_element = wait.until(EC.visibility_of_element_located(({by}, {self._py_str(value, {})})))')
                lines.append(f"    Select(select_element).select_by_visible_text({self._py_str(val, test_data)})")
            elif act == "check":
                by, value = self._py_selector(sel)
                lines.append(f'    checkbox = wait.until(EC.element_to_be_clickable(({by}, {self._py_str(value, {})})))')
                lines.append(f"    if not checkbox.is_selected():")
                lines.append(f"        checkbox.click()")
            elif act == "uncheck":
                by, value = self._py_selector(sel)
                lines.append(f'    checkbox = wait.until(EC.element_to_be_clickable(({by}, {self._py_str(value, {})})))')
                lines.append(f"    if checkbox.is_selected():")
                lines.append(f"        checkbox.click()")
            elif act == "assert_visible":
                by, value = self._py_selector(sel)
                lines.append(f'    wait.until(EC.visibility_of_element_located(({by}, {self._py_str(value, {})})))')
            elif act == "assert_text":
                by, value = self._py_selector(sel)
                clean_val = (val or "").replace('"', '\\"')
                lines.append(f'    element = wait.until(EC.visibility_of_element_located(({by}, {self._py_str(value, {})})))')
                lines.append(f'    assert "{clean_val}" in element.text, f"Expected \\"{clean_val}\\" in page text"')
            elif act == "assert_title":
                clean_val = (val or "").replace('"', '\\"')
                lines.append(f'    assert "{clean_val}".lower() in driver.title.lower(), f"Expected \\"{clean_val}\\" in page title"')
            elif act == "assert_url_contains":
                clean_val = (val or "").replace('"', '\\"')
                lines.append(f'    assert "{clean_val}" in driver.current_url, f"Expected \\"{clean_val}\\" in current URL"')
            lines.append("")

        # Post-condition checks
        if checks:
            lines.append("    # Post-Condition Assertions")
            for check in checks:
                ctype = check.get("type")
                cval = (check.get("value") or "").replace('"', '\\"')
                if ctype == "visible":
                    by, value = self._py_selector(cval)
                    lines.append(f'    wait.until(EC.visibility_of_element_located(({by}, "{value}")))')
                elif ctype == "text_contains":
                    lines.append(f'    assert "{cval}" in driver.find_element(By.TAG_NAME, "body").text')
                elif ctype == "title_contains":
                    lines.append(f'    assert "{cval}".lower() in driver.title.lower()')

        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _build_test_data(test_case: "TestCase", steps: list[dict]) -> dict[str, str]:
        case_test_data: dict[str, str] = {}
        raw_td = getattr(test_case, "test_data", None)
        if isinstance(raw_td, dict):
            case_test_data = {str(k): str(v) for k, v in raw_td.items() if not str(k).startswith("_")}
        elif isinstance(raw_td, str) and raw_td.strip():
            try:
                p_td = json.loads(raw_td)
                if isinstance(p_td, dict):
                    case_test_data = {str(k): str(v) for k, v in p_td.items() if not str(k).startswith("_")}
            except Exception:
                pass
        for step in steps:
            val = step.get("value") or ""
            for match in re.findall(r"\{\{\s*([A-Za-z0-9_.\-]+)\s*\}\}", val):
                tok = match.strip()
                if tok and tok not in case_test_data:
                    from app.services.ai_service import synthesize_parameter_value
                    case_test_data[tok] = synthesize_parameter_value(tok, getattr(test_case, "category", "positive"))
        return case_test_data
